<!--
WARNING: This file was autogenerated by MagicDraw MBRS plugin.
Do not update it because if you run generator again you changes will be deleted
-->
<html>
<head>
    <h1>Generated application</h1>
</head>
<body>
<ul>
    <#list allClasses as class>
        <li><a href="/${class.name?uncap_first}/all">See all ${class.name?uncap_first}s</a></li>
    </#list>
</ul>
</body>
</html>